#!/bin/bash

IMAGE=danielkelshaw/latex:full

if [[ $1 == "--dir" ]]; then
    dir=$(cd $(dirname $2); pwd)/$(basename $2)
    shift 2
else
    dir=$(pwd)
    shift
fi

if [[ ! -d $dir ]]; then
    echo "$dir must be a directory..."
    exit 1
fi

docker run --rm -i -v $dir:/data $IMAGE "$@"

