FROM ubuntu:20.04

# install basic packages
RUN apt-get update -q && \
    apt-get install -qy \
        texlive-full \
        python-pygments \
        gnuplot \
        make \
        git \
    && rm -rf /var/lib/apt/lists/*

# customise environment
ENV HOME /data
WORKDIR /data

VOLUME ["/data"]

